const fs = require('fs');

const reqRideEn = {
  "title": "Request Ride",
  "description": "Select your destination and calculate distance locally",
  "step1Title": "1. Select Destination",
  "governorate": "Governorate",
  "district": "District",
  "step2Title": "2. Destination Coordinates",
  "pickupPlaceholder": "Select an area or enter coordinates like 31.95, 35.91",
  "localCoordsTooltip": "Local coordinates without geocoding",
  "calculateBtn": "Calculate Distance & Fare",
  "calculatedLocally": "Distance calculated locally",
  "resetBtn": "Reset",
  "actualDistance": "Actual Distance",
  "blindSpot": "Blind spot area",
  "km": "km",
  "estimatedTime": "Estimated Time",
  "min": "min",
  "formulaTitle": "📐 Field Equity Formula V5.1",
  "haversine": "Great-circle distance (Haversine):",
  "tortuosity": "Local tortuosity factor (γ):",
  "approvedDistance": "Approved distance:",
  "timeCalc": "Time calculation (Distance / Speed 40 km/h):",
  "blindSpotWarning": "⚠️ Unable to extract coordinates; \"Blind Spot Protocol\" activated to ensure region-level radar continuity.",
  "step7Title": "7. Required Seats",
  "selectSeats": "Select seats",
  "passenger": "Passenger",
  "passengers": "Passengers",
  "step8Title": "8. Pricing Mode",
  "noPreference": "No Preference",
  "freePrice": "Free Price",
  "appPricing": "App Pricing",
  "taxiMeter": "Taxi Meter",
  "availabilityStatus": "Driver Availability Status",
  "supplyHigh": "🔴 Supply Momentum: High & Available",
  "demandHigh": "⚠️ High Demand: Requires Large Sedan",
  "integrityTitle": "Smart Radar Field Integrity",
  "integrityDesc": "Under the Zero Distraction and Zero Cloud Charter (SC55), Radar refrains from displaying maps to riders (technical blindness) or exceeding 1.5 km radius. Dimensions are computed frozen at zero commission.",
  "suspended": "Service is temporarily suspended by official directive",
  "sending": "Sending request...",
  "sendRequest": "Send Ride Request",
  "amman": "Amman",
  "wadiSeer": "Wadi Al-Seer",
  "wadiSeerAmman": "Wadi Al-Seer - Amman",
  "downtown": "Downtown",
  "downtownAmman": "Downtown - Amman",
  "zarqa": "Zarqa",
  "newZarqa": "New Zarqa",
  "irbid": "Irbid",
  "irbidDowntown": "Irbid Downtown",
  "madaba": "Madaba",
  "madabaDowntown": "Madaba Downtown"
};

const reqRideAr = {
  "title": "طلب رحلة",
  "description": "اختر وجهتك واحسب المسافة محلياً",
  "step1Title": "1. اختر الوجهة",
  "governorate": "المحافظة",
  "district": "المنطقة",
  "step2Title": "2. إحداثيات الوجهة",
  "pickupPlaceholder": "اختر منطقة أو اكتب الإحداثيات مثل 31.95, 35.91",
  "localCoordsTooltip": "إحداثيات محلية بدون geocoding",
  "calculateBtn": "حساب المسافة والسعر",
  "calculatedLocally": "تم حساب المسافة محلياً",
  "resetBtn": "إعادة الضبط",
  "actualDistance": "المسافة الفعلية",
  "blindSpot": "منطقة لاهوت",
  "km": "كم",
  "estimatedTime": "الزمن التقديري",
  "min": "دقيقة",
  "formulaTitle": "📐 معادلة العدالة الميدانية V5.1",
  "haversine": "مسافة الدورة العظمى (Haversine):",
  "tortuosity": "معامل التعرج المحلي (γ):",
  "approvedDistance": "المسافة المعتمدة:",
  "timeCalc": "حساب الزمن (المسافة / السرعة 40 كم/س):",
  "blindSpotWarning": "⚠️ تعذر استخراج الإحداثيات؛ تم تفعيل \"بروتوكول النقطة العمياء\" لتأمين استمرارية الرادار على مستوى المنطقة.",
  "step7Title": "7. عدد المقاعد المطلوبة",
  "selectSeats": "حدد المقاعد",
  "passenger": "راكب واحد",
  "passengers": "ركاب",
  "step8Title": "8. طريقة التسعير",
  "noPreference": "بدون تحديد",
  "freePrice": "سعر حر",
  "appPricing": "حسب تسعيرة التطبيق",
  "taxiMeter": "حسب عداد التاكسي",
  "availabilityStatus": "حالة توفر السائقون",
  "supplyHigh": "🔴 زخم العرض: صاعد ومتوفر",
  "demandHigh": "⚠️ زخم الطاقة: كثيف ويتطلب سيارة صالون واسعة",
  "integrityTitle": "النزاهة الميدانية لـ \"الرادار الذكي\"",
  "integrityDesc": "بموجب ميثاق صفر تشتت وصفر سحابة (SC55)، يمتنع الرادار عن عرض الخرائط للراكب نهائياً (العمى التقني) أو تجاوز فقاعة 1.5 كم. يتم السيطرة وحساب الأبعاد تجميداً بصفر عمولة.",
  "suspended": "الخدمة معلقة مؤقتاً بناءً على القرارات الرسمية",
  "sending": "يرسل الطلب...",
  "sendRequest": "إرسال طلب الرحلة",
  "amman": "عمان",
  "wadiSeer": "وادي السير",
  "wadiSeerAmman": "وادي السير - عمان",
  "downtown": "وسط البلد",
  "downtownAmman": "وسط البلد - عمان",
  "zarqa": "الزرقاء",
  "newZarqa": "الزرقاء الجديدة",
  "irbid": "إربد",
  "irbidDowntown": "إربد البلد",
  "madaba": "مأدبا",
  "madabaDowntown": "مأدبا البلد"
};

const updateFile = (path, newKey, newObj) => {
  const content = JSON.parse(fs.readFileSync(path, 'utf8'));
  content[newKey] = newObj;
  fs.writeFileSync(path, JSON.stringify(content, null, 2), 'utf8');
};

updateFile('d:/freelance/Radar/smart-radar-core/src/messages/en.json', 'requestRide', reqRideEn);
updateFile('d:/freelance/Radar/smart-radar-core/src/messages/ar.json', 'requestRide', reqRideAr);
console.log('done');
